name: math_and_cs
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - voila
  - pandas
  - numpy
  - scipy
  - tqdm
  - matplotlib
  - plotnine
  - nodejs
  - ipywidgets
  - jupytext
  - jupyterlab-spellchecker
  - mpmath
